swagger: '2.0'
info:
  title: 射击管理平台
  version: '1.0.0'
paths:
  /login:
    post:
      tags:
        - "auth"
      summary: 登录
      produces:
        - application/json
      parameters:
        - name: user
          in: body
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                description: 用户名
              password:
                type: string
                description: 密码
      responses:
        '200':
          description: 登录成功
          schema:
            type: object
            properties:
              code:
                type: integer
                description: 响应码
              msg:
                type: string
                description: 提示信息
              data:
                type: object
                properties:
                  token:
                    type: string
                    description: 登录凭证
                description: 数据

        '500':
          description: 添加用户失败
          schema:
            type: object
            properties:
              error:
                type: string

  /logout:
    get:
      summary: Get a greeting message
      produces:
        - application/json
      responses:
        '200':
          description: A greeting message
          schema:
            type: object
            properties:
              message:
                type: string


  /api/shooter/get:
    get:
      tags:
        - "射手"
      summary: 获取单个射手
      produces:
        - application/json
      parameters:
        - name: shooterId
          type: string
          in: path
          required: true

      responses:
        '200':
          description: 登录成功
          schema:
            type: object
            properties:
              code:
                type: integer
                description: 响应码
              msg:
                type: string
                description: 提示信息
              data:
                $ref: "#definitions/shooter"

  /api/shooter/list:
    get:
      tags:
        - "射手"
      summary: 获取射手列表
      produces:
        - application/json
      parameters:
        - name: id
          type: string
          in: query
        - name: name
          type: string
          in: query

      responses:
        '200':
          description: 登录成功
          schema:
            type: object
            properties:
              code:
                type: integer
                default: 200
                description: 响应码
              msg:
                type: string
                description: 提示信息
              data:
                type: array
                items:
                  $ref: "#definitions/shooter"

  /api/shooter/page:
    get:
      tags:
        - "射手"
      summary: 获取射手列表
      produces:
        - application/json
      parameters:
        - name: pageNum
          type: integer
          in: query
        - name: pageSize
          type: integer
          in: query
        - name: orderBy
          type: string
          in: query

      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              code:
                type: integer
                example: 200
                description: 响应码
              msg:
                type: string
                description: 提示信息
              data:
                $ref: "#definitions/shooter_page"

  /api/shooter/add:
    post:
      tags:
        - "射手"
      summary: 获取射手列表
      produces:
        - application/json
      parameters:
        - name: shooter
          in: body
          schema:
            $ref: "#definitions/shooter"

      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              code:
                type: integer
                description: 响应码
              msg:
                type: string
                description: 提示信息
              data:
                type: object

  /api/shooter/update:
    post:
      tags:
        - "射手"
      summary: 更新射手列表
      produces:
        - application/json
      parameters:
        - name: shooter
          in: body
          schema:
            $ref: "#definitions/shooter"

      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              code:
                type: integer
                description: 响应码
                example: 200
              msg:
                type: string
                description: 提示信息
              data:
                type: object

  /api/shooter/delete:
    delete:
      tags:
        - "射手"
      summary: 删除射手列表
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          type: string
          required: true

      responses:
        '200':
          description: success
          schema:
            type: object
            properties:
              code:
                type: integer
                description: 响应码
              msg:
                type: string
                description: 提示信息
              data:
                type: object
definitions:
  shooter:
    type: object
    properties:
      id:
        type: string
      name:
        type: string

  shooter_page:
    type: object
    properties:
      pageNum:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
      list:
        type: array
        items:
          $ref: "#definitions/shooter"
