HEADER1 = 0
HEADER2 = 1
HEADER3 = 2
DATA_FLAG = 3
"""坐标信息和射击信息flag"""
HIT_RING_NUMBER = 4
AIM_RING_NUMBER = 5
GUN_SHAKING = 6
GUN_SHAKING_RATE = 7
FIRE_SHAKING = 8
FIRE_SHAKING_RATE = 9
AXIS_X_INT_PART = 10
AXIS_X_DECIMAL_PART = 11
AXIS_Y_INT_PART = 12
AXIS_Y_DECIMAL_PART = 13
TAIL = 14
